name: appvelox_flutter_enterprise_core
description: "Appvelox Core"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  fl_chart: ^1.1.1
  google_fonts: ^6.3.3
  dio: ^5.9.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.2
  share_plus: ^12.0.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  go_router: ^17.0.1
  injectable: ^2.7.1+2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  build_runner: ^2.10.4
  injectable_generator: ^2.9.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  generate: true

  uses-material-design: true
